services:
  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8080"
    networks:
      - backend

  balance-service:
    depends_on:
      - account-service
    build:
      context: ./balance-service
    ports:
      - "8082:8080"
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:8080
    networks:
      - backend

networks:
  backend:
